import type { CaseStudy } from './types';

/**
 * Case studies. Copy is rewritten for this concept; the facts (clients, stacks,
 * outcomes and figures) come from the case studies published on thebyte9.com.
 */
export const caseStudies: CaseStudy[] = [
  {
    slug: 'dockwalk',
    client: 'Dockwalk',
    title: 'A superyacht crew community, rebuilt for growth',
    sector: 'Publishing',
    summary:
      'Dockwalk is the go-to community for superyacht crew. After moving to Blaze, its users grew by 817% and page views by 484%.',
    challenge:
      'Dockwalk needed faster publishing infrastructure, more control for its editors and better ways to earn from a loyal, global audience.',
    solution: [
      'Migrated the whole site onto the Blaze headless CMS.',
      'Searchable articles and directories, powered by Elasticsearch.',
      'A Superports directory that crew browse on an interactive Google Map.',
      'Contextual advertising through Google Ad Manager.',
      'Page Builder for the editorial team, plus analytics and audience segments.',
      'Serverless hosting on AWS.',
    ],
    stack: ['Blaze', 'Elasticsearch', 'Google Maps', 'Google Ad Manager', 'AWS serverless'],
    outcomes: [
      'More advertising revenue',
      'More subscription revenue',
      'Editors publish without waiting on developers',
    ],
    metrics: [
      { label: 'Users', value: 817, direction: 'up' },
      { label: 'Page views', value: 484, direction: 'up' },
      { label: 'Average time on page', value: 67, direction: 'up' },
      { label: 'Page performance', value: 38, direction: 'up' },
    ],
    featured: true,
    cover: 'waves',
    legacyPaths: ['/our-work/dockwalk-transform-digital-operations-with-blaze-cms'],
  },
  {
    slug: 'the-pharma-letter',
    client: 'The Pharma Letter',
    title: 'More readers and revenue for pharmaceutical news',
    sector: 'Publishing',
    summary:
      'The Pharma Letter reports on the global pharmaceutical industry. Leaving its proprietary CMS for Blaze more than tripled its active and new users.',
    challenge:
      'Ageing proprietary systems made every change slow and expensive, holding back both the newsroom and the commercial team.',
    solution: [
      'No-code page creation and management for editors.',
      'A headless Blaze CMS behind a single-page front end, served over GraphQL.',
      'AI-assisted content optimisation.',
      'Analytics and personalisation through Snowplow.',
      'Google Ad Manager for advertising.',
      'Serverless hosting on AWS, following MACH and Jamstack principles.',
    ],
    stack: ['Blaze', 'GraphQL', 'AWS serverless', 'Snowplow', 'Google Ad Manager'],
    outcomes: [
      'Stronger search rankings',
      'A faster, easier site to use',
      'Growth in advertising, directory, sponsorship and subscription revenue',
      'Simpler editorial workflows',
    ],
    metrics: [
      { label: 'New users', value: 253, direction: 'up' },
      { label: 'Active users', value: 225, direction: 'up' },
    ],
    year: 2024,
    featured: true,
    cover: 'masthead',
    legacyPaths: [
      '/our-work/the-pharma-letter-boosts-traffic-subscriptions-and-sponsorship-with-blaze',
      '/the-pharma-letter-case-study',
    ],
  },
  {
    slug: 'bear-and-bear',
    client: 'Bear & Bear',
    title: 'Headless WooCommerce, faster pages and 60% more revenue',
    sector: 'Ecommerce',
    summary:
      'We separated Bear & Bear’s WooCommerce engine from a new Blaze storefront. Pages load 47% faster and revenue is up 60% year on year.',
    challenge:
      'A monolithic ecommerce setup had become slow, rigid and costly to run, and it was holding back growth.',
    solution: [
      'Kept WooCommerce as the commerce engine, decoupled behind a Blaze storefront.',
      'Products and content managed side by side in the page builder.',
      'Component-level analytics and Elasticsearch-powered search.',
      'AWS elastic load balancing, provisioned with Terraform.',
      'Monitoring and code quality with Datadog, Sentry, Snyk and Codecov.',
      'Integrations with Mailchimp, Google Ad Manager and Bing Ads.',
    ],
    stack: [
      'Blaze',
      'WooCommerce',
      'GraphQL',
      'Elasticsearch',
      'AWS',
      'Terraform',
      'Datadog',
      'Sentry',
      'Snyk',
      'Codecov',
    ],
    outcomes: ['A more stable platform', 'Higher conversion', 'Lower running costs'],
    metrics: [
      { label: 'Page load time', value: 47, direction: 'down' },
      { label: 'Page views', value: 78, direction: 'up' },
      { label: 'Year-on-year revenue', value: 60, direction: 'up' },
      { label: 'Transactions', value: 37, direction: 'up' },
    ],
    quote: {
      text: 'Byte9 were able to react unbelievably quickly to transition our entire website to Blaze',
      name: 'Sam Gore',
      role: 'Owner, Bear & Bear',
    },
    featured: true,
    cover: 'catalogue',
    legacyPaths: [
      '/our-work/bear-and-bear-woocommerce-headless-stack',
      '/our-work/bear-and-bear-case-study',
      '/bear-and-bear-case-study',
    ],
  },
  {
    slug: 'kogan-page',
    client: 'Kogan Page',
    title: 'Headless ecommerce for a global business publisher',
    sector: 'Ecommerce',
    summary:
      'Kogan Page sells business books in more than 90 countries. Blaze now runs its storefront with Shopware behind it, so marketers mix stories and products freely.',
    challenge:
      'A monolithic Magento store slowed everything down: product updates lagged, personalisation was limited, integrations were brittle, and search and analytics fell behind a growing catalogue.',
    solution: [
      'A headless architecture: Blaze runs the storefront, Shopware handles commerce.',
      'A no-code page builder that blends editorial and product content on any page.',
      'Live listings with dynamic merchandising, pricing and stock.',
      'Personalised journeys by genre, topic and audience.',
      'Bibliographic data kept in sync through ONIX imports and Virtusales Biblio Live.',
      'WCAG 2.1 AA accessibility, built on semantic HTML and ARIA.',
      'First-party data shared with Mapp, CRM and email tools.',
    ],
    stack: ['Blaze', 'Shopware', 'React', 'ONIX', 'Virtusales Biblio Live', 'Mapp', 'Google Analytics'],
    outcomes: [
      'Campaigns go live faster',
      'Better organic search visibility',
      'Higher engagement and conversion',
      'Lower development costs',
    ],
    metrics: [],
    quote: {
      text: 'Easily the most productive relationship with any developer.',
      name: 'Katleen Richardson',
      role: 'Marketing Director, Kogan Page',
    },
    featured: true,
    cover: 'shelf',
    legacyPaths: [
      '/our-work/kogan-page-best-practice-headless-ecommerce-with-blaze-and-shopware',
      '/kogan-page-blaze-a-trail-in-publishing-with-headless-ecommerce',
      '/kogan-page-case-study',
    ],
  },
  {
    slug: 'three-rivers-district-council',
    client: 'Three Rivers District Council',
    title: 'Self-service first for a district council',
    sector: 'Public sector',
    summary:
      'Three Rivers District Council wanted residents to sort things out online, at any hour. Its new Blaze site is fast, accessible and updated by council staff.',
    challenge:
      'The council needed to reduce avoidable contact, improve accessibility and offer dependable self-service, without calling on developers for every content change.',
    solution: [
      'A headless Blaze CMS with an app-like single-page front end.',
      'A no-code page builder for council teams.',
      'Archive content reworked for search and accessibility.',
      'Personalised content, with a GraphQL API for content and media.',
      'Serverless, microservice hosting on AWS.',
    ],
    stack: ['Blaze', 'GraphQL', 'AWS serverless', 'Jamstack', 'MACH'],
    outcomes: [
      'More queries resolved first time, online',
      'Less avoidable contact',
      'Services available around the clock',
      'Faster updates without developers',
      'Quicker pages on every device',
    ],
    metrics: [],
    year: 2024,
    featured: true,
    cover: 'civic',
    legacyPaths: [
      '/our-work/digital-service-evolution-with-three-rivers-district-council',
      '/three-rivers-district-council-website-launched-on-blaze-platform',
    ],
  },
  {
    slug: 'partspak',
    client: 'PartsPak',
    title: 'The UK’s first headless build on Oracle NetSuite Commerce',
    sector: 'Ecommerce',
    summary:
      'PartsPak supplies packaging machinery and parts across Europe. We paired Blaze with Oracle NetSuite Commerce, the first headless build of its kind in the UK.',
    challenge:
      'PartsPak wanted to own its site day to day: better conversion, real-time personalisation, simple tools for non-technical staff, faster pages and a clean link to NetSuite.',
    solution: [
      'A Blaze storefront on Oracle NetSuite Commerce, synced in real time.',
      'No-code merchandising and personalisation for the commercial team.',
      'A single-page front end served through a GraphQL API.',
      'Elasticsearch-powered catalogue search and landing pages.',
      'First-party analytics via Snowplow and server-side Google Tag Manager.',
      'Audience segments for matched, targeted campaigns.',
    ],
    stack: ['Blaze', 'Oracle NetSuite Commerce', 'GraphQL', 'Elasticsearch', 'Snowplow', 'Google Tag Manager'],
    outcomes: [
      'Faster pages and better Core Web Vitals',
      'Higher conversion',
      'Improved search rankings',
      'Granular analytics for targeted marketing',
    ],
    metrics: [],
    year: 2024,
    featured: false,
    cover: 'parts',
    legacyPaths: ['/our-work/partspak-pioneer-headless-ecommerce-with-blaze-and-oracle-netsuite-commerce'],
  },
  {
    slug: 'get-the-gloss',
    client: 'Get the Gloss',
    title: 'Award-winning beauty publishing, run in-house',
    sector: 'Publishing',
    summary:
      'Get the Gloss is a health and beauty title. On Blaze, its own team runs everything from expert directories to ad placements, and traffic grows week on week.',
    challenge:
      'Conventional platforms such as WordPress, Drupal and Sitecore were static and costly to host and scale, and every change needed a designer or developer.',
    solution: [
      'A headless Blaze CMS with a single-page front end.',
      'Page Builder for managing the whole site.',
      'Searchable listings and expert directories on Elasticsearch.',
      'Flexible advertising and banner management.',
      'Google Tag Manager and BigQuery integrations.',
      'Delivery through AWS CloudFront and Elastic Beanstalk.',
    ],
    stack: ['Blaze', 'Elasticsearch', 'GraphQL', 'AWS CloudFront', 'AWS Elastic Beanstalk', 'BigQuery'],
    outcomes: [
      'Consistent week-on-week traffic growth',
      'More time spent on site',
      'Stronger advertiser and sponsor engagement',
      'Strong Core Web Vitals',
      'Far less reliance on outside developers',
    ],
    metrics: [],
    quote: {
      text: 'The website is fabulous, looks stunning and we are seeing more visitors',
      name: 'Editor',
      role: 'Get the Gloss',
    },
    featured: false,
    cover: 'masthead',
    legacyPaths: ['/our-work/get-the-gloss-case-study'],
  },
  {
    slug: 'boat-international',
    client: 'Boat International Media',
    title: 'Maritime publishing with editors in control',
    sector: 'Publishing',
    summary:
      'Boat International Media publishes for the superyacht world. Blaze gave its editors the whole site and its commercial team precise, personalised advertising.',
    challenge:
      'The publisher wanted more editorial control and better performance, and to stop relying on dated proprietary CMS tools.',
    solution: [
      'Page-builder tools driving a single-page front end.',
      'Google Ad Manager integration for personalised advertising.',
      'Engagement data captured at page-component level.',
      'Personalisation for different reader groups.',
    ],
    stack: ['Blaze', 'GraphQL', 'AWS', 'Google Ad Manager'],
    outcomes: [
      'Faster, cheaper site development',
      'Higher reader engagement',
      'More advertising and sponsorship revenue',
      'A site that evolves without developer bottlenecks',
    ],
    metrics: [],
    year: 2023,
    featured: false,
    cover: 'waves',
    legacyPaths: [
      '/our-work/byte9-and-boat-international-media-pioneer-maritime-digital-publishing-with-blaze-cms',
    ],
  },
  {
    slug: 'intelligent-insurer',
    client: 'Intelligent Insurer',
    title: 'Reach and ad yield for a global insurance title',
    sector: 'Publishing',
    summary:
      'Intelligent Insurer covers the global insurance market. Its team now builds pages without developers, and advertisers reach readers by context and segment.',
    challenge:
      'It needed more editorial control, better performance and content tailored to readers around the world.',
    solution: [
      'No-code page templates for business users.',
      'Archive content enriched with metadata, structured data and categories.',
      'An app-like single-page front end with related-content navigation.',
      'Contextual ad classification through Google Ad Manager.',
      'Real-time engagement data and audience segments via Snowplow.',
    ],
    stack: ['Blaze', 'Google Ad Manager', 'Snowplow'],
    outcomes: [
      'Wider reach and engagement',
      'Less development time and cost',
      'Better ad yield and sponsor return',
      'Longer sessions and more subscriptions',
    ],
    metrics: [],
    year: 2024,
    featured: false,
    cover: 'masthead',
    legacyPaths: ['/our-work/intelligent-insurer-launches-on-blaze-cms'],
  },
  {
    slug: 'halldale',
    client: 'Halldale',
    title: 'A publishing power-up for simulation and training news',
    sector: 'Publishing',
    summary:
      'Halldale covers the simulation and training industry. We moved its content onto Blaze with richer metadata, so editors build landing pages themselves.',
    challenge:
      'Halldale wanted modern publishing tools, more editorial control and content that readers could find more easily.',
    solution: [
      'Migration from a legacy CMS, with enhanced metadata and structured data.',
      'Page-builder tools for rich landing pages.',
      'Real-time engagement tracking and personalisation via Snowplow.',
      'Contextual ad classification with Google Ad Manager.',
    ],
    stack: ['Blaze', 'Snowplow', 'Google Ad Manager'],
    outcomes: [
      'Wider reach',
      'More reader and sponsor engagement',
      'Lower development cost and time',
      'A faster site and more traffic',
    ],
    metrics: [],
    featured: false,
    cover: 'masthead',
    legacyPaths: ['/our-work/halldale-power-up-digital-publishing-with-blaze-cms'],
  },
  {
    slug: 'informa',
    client: 'Informa',
    title: 'Business intelligence by voice, on Alexa',
    sector: 'Voice',
    summary:
      'Informa, the FTSE 100 intelligence, events and research group, wanted its expertise available by voice. We built serverless Alexa skills for podcasts, news and questions to its analysts.',
    challenge:
      'Working with Amazon, Informa set out to open up its business intelligence and expert consultations through voice.',
    solution: [
      'A serverless Alexa skill to search and play Informa podcasts via SoundCloud.',
      'Ask the Analyst, letting subscribers send questions to Informa experts.',
      'Pharma and MedTech news flash briefings.',
      'Multi-language support for a global audience.',
      'Built test-first on AWS Lambda with Node.js, deployed through CloudFormation and CodePipeline.',
    ],
    stack: ['AWS Lambda', 'Node.js', 'Alexa Skills Kit', 'SoundCloud', 'DynamoDB', 'CloudFormation', 'CodePipeline'],
    outcomes: [
      'Three live skills: Pharma Intelligence podcasts, Pharma News and MedTech News',
      'Pay-per-use running costs',
      'Scales automatically with demand',
    ],
    metrics: [],
    year: 2020,
    featured: false,
    cover: 'waveform',
    legacyPaths: ['/informa-case-study'],
  },
];
