import type { Job } from './types';

export const jobs: Job[] = [
  {
    slug: 'business-development-manager',
    title: 'Business Development Manager',
    reportsTo: 'Managing Director',
    salary: 'Market leading, with a strong commission opportunity',
    location: 'London (Putney)',
    summary:
      'Grow Blaze by helping organisations move from legacy CMS and ecommerce platforms to something faster, more flexible and easier to run.',
    responsibilities: [
      'Own the sales pipeline, from first opportunity to signed contract.',
      'Explain the business case for Blaze to senior decision-makers.',
      'Run product demos and present relevant case studies.',
      'Analyse requirements and recommend technical solutions.',
      'Build lasting relationships with executives at prospects and clients.',
      'Keep the CRM current and report on forecasts.',
      'Keep marketing collateral up to date.',
    ],
    skills: [
      'At least 5 years in pre-sales or business development at a software or technology consultancy',
      'Experience selling CMS and ecommerce development, ideally from an agency',
      'Understanding of enterprise application integration',
      'Familiarity with agile delivery (Scrum, Jira) and CI/CD',
      'Working knowledge of AWS or a similar cloud platform',
      'Confident presenting, strong with spreadsheets and a clear problem-solver',
    ],
    niceToHave: ['Room to grow into a wider business development and marketing team'],
    urgent: true,
    legacyPaths: ['/business-development-manager'],
  },
  {
    slug: 'junior-front-end-developer',
    title: 'Junior Front End Developer',
    reportsTo: 'Technical Project Manager',
    salary: 'Market leading, depending on experience',
    location: 'London',
    summary:
      'Support our design and development teams by turning designs into front-end code across several client projects, as part of a pair and LAMP team.',
    responsibilities: [
      'Produce front-end code for multiple client projects.',
      'Turn UX wireframes and design mock-ups into well-organised front-end sites.',
      'Work closely with designers, back-end developers and QA.',
      'Make sure everything works across devices and browsers.',
      'Plan and deliver several projects at once, often to tight deadlines.',
    ],
    skills: [
      'Excellent HTML, CSS and JavaScript',
      'Valid HTML5 and CSS3/4 markup',
      'Cross-browser, cross-platform development',
      'SASS and BEM coding standards',
      'Version control with Git',
      'A JavaScript framework such as AngularJS or React',
    ],
    niceToHave: [
      'Testing frameworks such as Jest, Mocha or Chai',
      'Isomorphic React applications',
      'Working with APIs and GraphQL',
      'Knowledge of mobile environments, especially iOS and Android',
      'Node.js',
    ],
    urgent: false,
    legacyPaths: ['/junior-front-end-developer'],
  },
  {
    slug: 'senior-front-end-javascript-developer',
    title: 'Senior Front-end JavaScript Developer',
    reportsTo: 'Technical Project Manager',
    salary: 'Negotiable, depending on experience',
    location: 'London, with remote working available',
    summary:
      'Write sophisticated, performant front-end code for Blaze and our client implementations, and help the wider team raise its game.',
    responsibilities: [
      'Build performant front ends for feature-rich web applications.',
      'Work with design and development on interfaces and performance.',
      'Mentor junior front-end developers and champion best practice.',
      'Turn wireframes and mock-ups into well-organised interfaces.',
      'Collaborate with QA, DevOps and back-end developers.',
    ],
    skills: [
      'At least 4 years of commercial front-end development',
      'HTML, CSS and JavaScript, with React, Angular or Express',
      'Node.js and Flux-style state management such as Redux',
      'GraphQL and REST APIs',
      'npm, Gulp and Webpack',
      'Test-driven development and Git',
      'SASS and BEM, web accessibility, Bootstrap and mobile',
      'Example work on GitHub',
    ],
    niceToHave: [
      'iOS or Android development',
      'TypeScript',
      'AWS or Google Cloud',
      'Docker or Kubernetes',
      'CI and testing tools',
      'CMS platforms such as WordPress, Magento or Drupal',
    ],
    urgent: false,
    legacyPaths: ['/senior-front-end-web-developer'],
  },
  {
    slug: 'technical-project-manager',
    title: 'Technical Project Manager',
    reportsTo: 'Operations',
    salary: 'Market leading, depending on experience',
    location: 'London, hybrid (2–3 office days a week); remote within Europe considered',
    summary:
      'Lead delivery of Blaze product development and client implementations, balancing scope, budget, time and people.',
    responsibilities: [
      'Oversee delivery of product work and client and partner implementations.',
      'Work with development, DevOps and product teams for predictable releases.',
      'Manage client budgets alongside account management.',
      'Plan, allocate and report on resources.',
      'Keep quality high and internal and third-party contributors coordinated.',
      'Produce clear project documentation.',
    ],
    skills: [
      'Agile project management with Jira, Confluence and GitHub',
      'Complex software projects with many stakeholders',
      'Solid grasp of the software development lifecycle and third-party resourcing',
      'Kanban and Scrum, including their ceremonies',
      'Tender management',
      'People management and process improvement',
    ],
    niceToHave: [
      'Accreditation, audit and training experience',
      'Familiarity with Node.js, React, AWS and Docker',
      'Agency experience',
    ],
    urgent: false,
    legacyPaths: ['/technical-project-manager'],
  },
  {
    slug: 'senior-web-designer',
    title: 'Senior Web Designer',
    reportsTo: 'Technical Project Manager and Managing Director',
    salary: 'Depending on experience',
    location: 'London (Putney office)',
    summary:
      'Take product and client work from idea and wireframes through to high-fidelity design, for Blaze and the sites built on it.',
    responsibilities: [
      'Design new features across complete customer journeys.',
      'Improve existing experiences for engagement and conversion.',
      'Validate designs with analytics data.',
      'Contribute to style guides and design systems.',
      'Present designs and the reasoning behind them.',
      'Work with developers to deliver the finished experience.',
    ],
    skills: [
      'At least 5 years as a digital, UX or UI designer',
      'Responsive and adaptive web design, ideally including web apps',
      'Strong web typography and knowledge of design patterns',
      'Accessibility, usability and brand guidelines',
      'Agile and Scrum',
      'Sketch, Zeplin, Photoshop, Illustrator and InVision',
      'HTML, CSS and SASS for prototyping',
      'CMS or ecommerce tools such as WordPress, Drupal, Shopify, Magento or BigCommerce',
    ],
    niceToHave: ['Comfortable in client meetings and calm under deadline pressure'],
    urgent: false,
    legacyPaths: ['/senior-web-designer'],
  },
];
